export const ERROR_CODES = {
  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // OTP (phone via SMS, email via SMTP)
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",
  OTP_ALREADY_SENT: "OTP_ALREADY_SENT",
  // The channel was never verified, or the verification window lapsed
  // before registration completed.
  OTP_NOT_VERIFIED: "OTP_NOT_VERIFIED",

  // Credentials and registration
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  PHONE_ALREADY_REGISTERED: "PHONE_ALREADY_REGISTERED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",

  // Session
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  // An already-rotated refresh token was replayed: the whole token family
  // is revoked and every session for that user ends.
  REFRESH_REUSE_DETECTED: "REFRESH_REUSE_DETECTED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CSRF_HEADER_MISSING: "CSRF_HEADER_MISSING",

  // Account state
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",
  ONBOARDING_INCOMPLETE: "ONBOARDING_INCOMPLETE",

  // Google OAuth
  OAUTH_STATE_INVALID: "OAUTH_STATE_INVALID",
  OAUTH_EMAIL_MISMATCH: "OAUTH_EMAIL_MISMATCH",
  OAUTH_ROLE_NOT_ALLOWED: "OAUTH_ROLE_NOT_ALLOWED",

  // Profile
  PORTFOLIO_LINK_NOT_ALLOWED: "PORTFOLIO_LINK_NOT_ALLOWED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
